image: "debian:stable-slim"
stages:
  - build
  - test
  - release

variables:
  WEBSITE_REPO_TRIGGER: "https://gitlab.com/api/v4/projects/125326/trigger/pipeline"
  WEBSITE_REPO_BRANCH: "master"

build-branch:
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip
    - pip3 install -r requirements.txt
  script:
    - make otf ttf webfonts
  artifacts:
    paths:
    - build/
  except:
    - tags

build-tag:
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip zip
    - pip3 install -r requirements.txt
  script:
    - make ttf otf webfonts
    - sh tools/artifacts.sh
  artifacts:
    paths:
    - build/
  only:
    - tags

test:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y make libharfbuzz-bin python3-pip
    - pip3 install -r requirements.txt
  script:
    - make test

release:
  image: "pstauffer/curl:latest"
  stage: release
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=${WEBSITE_REPO_BRANCH} "${WEBSITE_REPO_TRIGGER}"
  only:
    - tags
