image: "debian:stretch"

build:
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip
    - pip3 install -r requirements.txt
  script:
    - make compile webfonts
  artifacts:
    paths:
    - build/

test:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y make libharfbuzz-bin
  script:
    - make test
